#!/usr/bin/python

import sys, getopt
import aerofiles.seeyou

from aerofiles.seeyou.reader import (
            Reader as OpenAirReader
            )

cupfile = OpenAirReader()
print sys.argv[1]
cupfile.read(open(str(sys.argv[1])))
